### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by Artist76** [j-hc/revanced-magisk-module#134]
App name is weird, magisk module
![Screenshot_2022-12-31-22-04-56-687_com miui home](https://user-images.githubusercontent.com/92868911/210159927-5c77cec5-5145-45f2-8d1d-e9a29bca8945.jpg)

**Comment by j-hc** [comment]
send me the output of this command if you didnt reinstall the module:
`su -c ls -l $(su -c pm path com.google.android.youtube | cut -d':' -f2 | sed 's/base.apk//g')`

**Comment by Artist76** [comment]
I got this

**Comment by Artist76** [comment]
![Screenshot_2023-01-01-11-01-21-697_com termux](https://user-images.githubusercontent.com/92868911/210480112-9eef72b5-cba4-4154-8a19-ace26b8a5b0d.jpg)

**Comment by j-hc** [comment]
should be fixed

**Comment by Artist76** [comment]
I downloaded the lastest version on github and its not fixed

**Comment by j-hc** [comment]
@Artist76 apply this in termux: `su -c "sed -i '7s/.*/sleep 15/' /data/adb/modules/ytrv-magisk/service.sh"` and let me know if its fixed
